=== forzec/l-server/gameserver/data/moveroute/moveroute.dtd
<!ELEMENT list (moveroute)*>
<!ELEMENT moveroute (node)*>
<!ATTLIST moveroute
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	is_running CDATA #IMPLIED>
<!ELEMENT node (#PCDATA)>
<!ATTLIST node
	chat_type CDATA #IMPLIED
	delay CDATA #IMPLIED
	npc_string CDATA #IMPLIED
	social CDATA #IMPLIED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>

=== forzec/l-server/gameserver/data/moveroute/gludio_airport.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "moveroute.dtd">
<list>
	<moveroute name="gludio_airport1" type="CIRCLE">
		<node x="-149268" y="254124" z="-184" />
		<node x="-148700" y="254399" z="-184" />
		<node x="-148313" y="254841" z="-184" />
		<node x="-148256" y="255338" z="-184" />
	</moveroute>
	<moveroute name="gludio_airport2" type="CIRCLE">
		<node x="-149469" y="254124" z="-184" />
		<node x="-150054" y="254373" z="-184" />
		<node x="-150431" y="254837" z="-184" />
		<node x="-150437" y="255335" z="-184" />
	</moveroute>
	<moveroute name="gludio_airport3" type="CIRCLE">
		<node x="-149239" y="254100" z="-184" />
		<node x="-148671" y="254375" z="-184" />
		<node x="-148284" y="254817" z="-184" />
		<node x="-148227" y="255314" z="-184" />
	</moveroute>
	<moveroute name="gludio_airport4" type="CIRCLE">
		<node x="-149499" y="254101" z="-184" />
		<node x="-150085" y="254350" z="-184" />
		<node x="-150462" y="254813" z="-184" />
		<node x="-150504" y="255312" z="-184" />
	</moveroute>
</list>

=== forzec/l-server/gameserver/data/moveroute/lesser_greater_evils.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "moveroute.dtd">
<list>
	<moveroute name="malign_conveyor_1_1" type="ONCE" is_running="true">
		<node x="27886" y="248609" z="-3208" />
		<node x="28150" y="247726" z="-3272" />
		<node x="27340" y="246649" z="-3680" />
		<node x="27646" y="245922" z="-3672" />
		<node x="28072" y="245912" z="-3696" /> <!-- DS: добавлено для корректного отображения -->
		<node x="28247" y="245907" z="-2552" />
		<node x="29074" y="245889" z="-3672" />
		<node x="29182" y="244811" z="-3688" />
		<node x="28920" y="244456" z="-3696" /> <!-- DS: добавлено для корректного отображения -->
		<node x="28770" y="244248" z="-2496" />
	</moveroute>
	<moveroute name="malign_conveyor_1_2" type="ONCE" is_running="true">
		<node x="26144" y="246444" z="-3208" />
		<node x="28063" y="247940" z="-3248" />
		<node x="28276" y="247756" z="-3272" />
		<node x="27344" y="246649" z="-3680" />
		<node x="27652" y="245914" z="-3688" />
		<node x="28072" y="245912" z="-3696" /> <!-- DS: добавлено для корректного отображения -->
		<node x="28255" y="245912" z="-2552" />
	</moveroute>
	<moveroute name="malign_conveyor_1_3" type="ONCE" is_running="true">
		<node x="27336" y="246216" z="-3656" />
		<node x="27645" y="245921" z="-3672" />
		<node x="28072" y="245912" z="-3696" /> <!-- DS: добавлено для корректного отображения -->
		<node x="28245" y="245904" z="-2552" />
	</moveroute>
	<moveroute name="malign_conveyor_1_4" type="ONCE" is_running="true">
		<node x="28476" y="245914" z="-3696" />
		<node x="29058" y="245984" z="-3672" />
		<node x="29433" y="245216" z="-3688" />
		<node x="28942" y="244492" z="-3696" />
	</moveroute>
	<moveroute name="malign_conveyor_2_1" type="ONCE" is_running="true">
		<node x="28771" y="244151" z="-2496" />
		<node x="28495" y="243839" z="-3696" />
		<node x="28727" y="242939" z="-3592" />
		<node x="28188" y="242512" z="-3464" />
		<node x="27248" y="242797" z="-3168" />
		<node x="26850" y="243834" z="-2896" />
		<node x="24636" y="246593" z="-1968" />
		<node x="24519" y="248586" z="-1936" />
		<node x="23094" y="250031" z="-1976" />
		<node x="22673" y="251605" z="-1992" />
		<node x="24560" y="254414" z="-1984" />
		<node x="25392" y="255459" z="-1992" />
	</moveroute>
</list>

=== forzec/l-server/gameserver/data/moveroute/drake_leaders.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "moveroute.dtd">
<list>
	<moveroute name="anta01" type="LOOP" is_running="true">
		<node x="144588" y="114415" z="-3712" />
		<node x="145028" y="113964" z="-3720" />
		<node x="145565" y="112796" z="-3720" />
		<node x="147292" y="112298" z="-3720" />
		<node x="148870" y="112879" z="-3720" />
		<node x="149289" y="114446" z="-3720" />
		<node x="148699" y="115797" z="-3720" />
		<node x="147622" y="116455" z="-3696" />
		<node x="146089" y="116189" z="-3720" />
		<node x="145478" y="115466" z="-3720" />
	</moveroute>
	<moveroute name="anta02" type="LOOP" is_running="true">
		<node x="147121" y="116447" z="-3704" />
		<node x="145821" y="116127" z="-3720" />
		<node x="145068" y="115317" z="-3720" />
		<node x="145179" y="114573" z="-3720" />
		<node x="145000" y="113473" z="-3720" />
		<node x="145932" y="112608" z="-3720" />
		<node x="146666" y="112633" z="-3720" />
		<node x="147091" y="112393" z="-3720" />
		<node x="148426" y="111834" z="-3720" />
		<node x="149058" y="112739" z="-3720" />
		<node x="149142" y="114352" z="-3720" />
		<node x="149043" y="115349" z="-3720" />
		<node x="148261" y="116040" z="-3720" />
	</moveroute>
	<moveroute name="anta03" type="LOOP" is_running="true">
		<node x="149046" y="115713" z="-3704" />
		<node x="148057" y="116273" z="-3720" />
		<node x="146962" y="116166" z="-3720" />
		<node x="146389" y="116343" z="-3720" />
		<node x="145427" y="115092" z="-3720" />
		<node x="145046" y="115063" z="-3720" />
		<node x="144970" y="114122" z="-3720" />
		<node x="145268" y="113186" z="-3720" />
		<node x="145917" y="112638" z="-3720" />
		<node x="147622" y="112236" z="-3720" />
		<node x="148443" y="111807" z="-3720" />
		<node x="149182" y="113166" z="-3720" />
		<node x="149326" y="114798" z="-3720" />
	</moveroute>
	<moveroute name="anta04" type="LOOP" is_running="true">
		<node x="148969" y="112462" z="-3720" />
		<node x="149307" y="114122" z="-3720" />
		<node x="149288" y="115027" z="-3720" />
		<node x="149201" y="115569" z="-3704" />
		<node x="147999" y="116333" z="-3720" />
		<node x="147147" y="116334" z="-3712" />
		<node x="146400" y="116303" z="-3720" />
		<node x="145724" y="116099" z="-3720" />
		<node x="145416" y="115539" z="-3720" />
		<node x="144759" y="115017" z="-3720" />
		<node x="145048" y="114051" z="-3720" />
		<node x="145052" y="113345" z="-3720" />
		<node x="145946" y="112652" z="-3720" />
		<node x="146742" y="112671" z="-3720" />
		<node x="147298" y="112206" z="-3720" />
		<node x="148285" y="111836" z="-3720" />
		<node x="148868" y="112217" z="-3720" />
	</moveroute>
	<moveroute name="anta05" type="LOOP" is_running="true">
		<node x="146396" y="112467" z="-3720" />
		<node x="147275" y="112366" z="-3720" />
		<node x="148404" y="111708" z="-3720" />
		<node x="149011" y="112200" z="-3720" />
		<node x="148978" y="112976" z="-3720" />
		<node x="149389" y="114042" z="-3720" />
		<node x="149190" y="115059" z="-3720" />
		<node x="148757" y="115760" z="-3720" />
		<node x="148243" y="115972" z="-3720" />
		<node x="147309" y="116338" z="-3704" />
		<node x="146711" y="116448" z="-3720" />
		<node x="146132" y="116125" z="-3720" />
		<node x="145514" y="115844" z="-3720" />
		<node x="144996" y="114996" z="-3720" />
		<node x="144919" y="114193" z="-3720" />
		<node x="145296" y="113303" z="-3720" />
		<node x="145900" y="112548" z="-3720" />
	</moveroute>
	<moveroute name="anta06" type="LOOP" is_running="true">
		<node x="145243" y="115607" z="-3720" />
		<node x="144847" y="115093" z="-3720" />
		<node x="144861" y="114199" z="-3720" />
		<node x="145144" y="113171" z="-3720" />
		<node x="145911" y="112548" z="-3720" />
		<node x="146522" y="112680" z="-3720" />
		<node x="147183" y="112253" z="-3720" />
		<node x="148265" y="111844" z="-3720" />
		<node x="148866" y="112217" z="-3720" />
		<node x="149181" y="113493" z="-3720" />
		<node x="149235" y="115266" z="-3720" />
		<node x="148119" y="116207" z="-3720" />
		<node x="146757" y="116484" z="-3712" />
		<node x="145609" y="115952" z="-3720" />
	</moveroute>
	<moveroute name="anta07" type="LOOP" is_running="true">
		<node x="147470" y="112233" z="-3720" />
		<node x="148062" y="112676" z="-3720" />
		<node x="148825" y="112787" z="-3720" />
		<node x="149111" y="114411" z="-3720" />
		<node x="149144" y="115414" z="-3720" />
		<node x="147399" y="116543" z="-3696" />
		<node x="146176" y="116041" z="-3720" />
		<node x="144933" y="115060" z="-3720" />
		<node x="145177" y="113945" z="-3720" />
		<node x="145195" y="113291" z="-3720" />
		<node x="146235" y="112582" z="-3720" />
		<node x="147183" y="112277" z="-3720" />
	</moveroute>
	<moveroute name="anta08" type="LOOP" is_running="true">
		<node x="148061" y="115909" z="-3720" />
		<node x="147307" y="116433" z="-3704" />
		<node x="146655" y="116399" z="-3720" />
		<node x="146032" y="115995" z="-3720" />
		<node x="145633" y="116057" z="-3720" />
		<node x="144925" y="115154" z="-3720" />
		<node x="144808" y="114123" z="-3720" />
		<node x="145036" y="113883" z="-3720" />
		<node x="145096" y="113268" z="-3720" />
		<node x="145787" y="112631" z="-3720" />
		<node x="146682" y="112832" z="-3720" />
		<node x="147141" y="112184" z="-3720" />
		<node x="148343" y="111922" z="-3720" />
		<node x="149016" y="112619" z="-3720" />
		<node x="149372" y="114234" z="-3720" />
		<node x="149286" y="115316" z="-3720" />
		<node x="148599" y="115938" z="-3720" />
	</moveroute>
	<moveroute name="anta09" type="LOOP" is_running="true">
		<node x="149090" y="114015" z="-3720" />
		<node x="149261" y="115199" z="-3720" />
		<node x="148620" y="116040" z="-3720" />
		<node x="147396" y="116408" z="-3704" />
		<node x="146526" y="116372" z="-3720" />
		<node x="145452" y="115861" z="-3720" />
		<node x="144951" y="115161" z="-3720" />
		<node x="145011" y="113841" z="-3720" />
		<node x="145332" y="113052" z="-3720" />
		<node x="146005" y="112544" z="-3720" />
		<node x="146795" y="112506" z="-3720" />
		<node x="148371" y="111951" z="-3720" />
		<node x="149008" y="112730" z="-3720" />
		<node x="149184" y="113764" z="-3720" />
	</moveroute>
</list>

=== forzec/l-server/gameserver/data/moveroute/hf_prophets.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "moveroute.dtd">
<list>
	<moveroute name="hf_prophet_gludio" type="CIRCLE">
		<node x="-13095" y="122262" z="-2984" />
		<node x="-13892" y="122266" z="-2984" chat_type="NPC_ALL" npc_string="A_BLACK_MOON_NOW_DO_YOU_UNDERSTAND_THAT_HE_HAS_OPENED_HIS_EYES" />
		<node x="-14148" y="121679" z="-2984" />
		<node x="-14153" y="121252" z="-2984" chat_type="NPC_ALL" npc_string="CLOUDS_OF_BLOOD_ARE_GATHERING_SOON_IT_WILL_START_TO_RAIN_THE_RAIN_OF_CRIMSON_BLOOD" />
		<node x="-13667" y="121247" z="-2984" />
		<node x="-14566" y="121247" z="-2984" />
		<node x="-14162" y="121268" z="-2984" chat_type="NPC_ALL" npc_string="WHILE_THE_FOOLISH_LIGHT_WAS_ASLEEP_THE_DARKNESS_WILL_AWAKEN_FIRST_UH" />
	</moveroute>
	<moveroute name="hf_prophet_giran" type="CIRCLE">
		<node x="83510" y="148636" z="-3400" />
		<node x="83679" y="147701" z="-3400" chat_type="NPC_ALL" npc_string="IT_IS_THE_DEEPEST_DARKNESS_WITH_ITS_ARRIVAL_THE_WORLD_WILL_SOON_DIE" />
		<node x="84858" y="147764" z="-3400" chat_type="NPC_ALL" npc_string="DEATH_IS_JUST_A_NEW_BEGINNING_HUHU_FEAR_NOT" />
		<node x="83623" y="147705" z="-3400" />
		<node x="83626" y="149551" z="-3400" chat_type="NPC_ALL" npc_string="AHH_BEAUTIFUL_GODDES_OF_DEATH_COVER_OVER_THE_FILTH_OF_THOS_WORLD_YOUR_DARKNESS" />
		<node x="83839" y="149549" z="-3400" />
	</moveroute>
	<moveroute name="hf_prophet_aden" type="CIRCLE">
		<node x="147436" y="25809" z="-2008" />
		<node x="146358" y="25810" z="-2008" chat_type="NPC_ALL" npc_string="THE_GODDESS_RESURRECTION_HAS_ALREADY_BEGUN_HUHU_INSIGNIFICANT_CREATURES_LIKE_YOU_CAN_DO_NOTHING" />
		<node x="146363" y="24145" z="-2008" chat_type="NPC_ALL" npc_string="A_BLACK_MOON_NOW_DO_YOU_UNDERSTAND_THAT_HE_HAS_OPENED_HIS_EYES" />
		<node x="146339" y="25823" z="-2008" />
		<node x="148546" y="25817" z="-2008" chat_type="NPC_ALL" npc_string="CLOUDS_OF_BLOOD_ARE_GATHERING_SOON_IT_WILL_START_TO_RAIN_THE_RAIN_OF_CRIMSON_BLOOD" />
	</moveroute>
	<moveroute name="hf_prophet_rune" type="CIRCLE">
		<node x="43381" y="-46796" z="-800" />
		<node x="43302" y="-47413" z="-792" chat_type="NPC_ALL" npc_string="WHILE_THE_FOOLISH_LIGHT_WAS_ASLEEP_THE_DARKNESS_WILL_AWAKEN_FIRST_UH" />
		<node x="43511" y="-48083" z="-792" />
		<node x="45208" y="-47955" z="-792" chat_type="NPC_ALL" npc_string="IT_IS_THE_DEEPEST_DARKNESS_WITH_ITS_ARRIVAL_THE_WORLD_WILL_SOON_DIE" />
		<node x="45902" y="-48181" z="-792" chat_type="NPC_ALL" npc_string="DEATH_IS_JUST_A_NEW_BEGINNING_HUHU_FEAR_NOT" />
		<node x="45203" y="-47980" z="-792" />
		<node x="43531" y="-48109" z="-792" />
		<node x="43319" y="-47412" z="-792" />
		<node x="43388" y="-46821" z="-800" />
	</moveroute>
</list>
