=== forzec/l-server/gameserver/data/random_town_points.dtd
<?xml version='1.0' encoding='utf-8'?>
<!ELEMENT list (town)*>
<!ELEMENT town (point)*>
<!ATTLIST town
	id CDATA #REQUIRED
	name CDATA #REQUIRED>
<!ELEMENT point (#PCDATA)>
<!ATTLIST point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	h CDATA #IMPLIED>

=== forzec/l-server/gameserver/data/random_town_points.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "random_town_points.dtd">
<list>
	<town id="1" name="Gludio">
		<point x="-16424" y="124504" z="-3112" h="57343" />
		<point x="-16056" y="124920" z="-3120" h="21220" />
		<point x="-15160" y="125384" z="-3128" h="32767" />
		<point x="-14952" y="124808" z="-3120" h="21220" />
		<point x="-15160" y="125720" z="-3136" h="49151" />
		<point x="-14776" y="125288" z="-3136" h="0" />
		<point x="-14632" y="126296" z="-3136" h="57343" />
		<point x="-14088" y="125224" z="-3128" h="32767" />
		<point x="-13464" y="124808" z="-3120" h="21220" />
		<point x="-13624" y="125416" z="-3136" h="57343" />
		<point x="-13240" y="126024" z="-3136" h="4836" />
		<point x="-13800" y="125768" z="-3136" h="16383" />
		<point x="-12952" y="125112" z="-3128" h="4836" />
		<point x="-12840" y="124712" z="-3120" h="0" />
		<point x="-12408" y="124728" z="-3112" h="32767" />
		<point x="-12888" y="124280" z="-3112" h="0" />
		<point x="-12264" y="123864" z="-3096" h="57343" />
		<point x="-12120" y="123304" z="-3088" h="32767" />
		<point x="-12936" y="123352" z="-3112" h="0" />
		<point x="-12120" y="122648" z="-3088" h="32767" />
		<point x="-12344" y="121640" z="-2984" h="8191" />
		<point x="-12920" y="122056" z="-2984" h="16383" />
		<point x="-13880" y="121512" z="-2984" h="40959" />
		<point x="-14904" y="121224" z="-2984" h="11547" />
		<point x="-15080" y="122952" z="-3112" h="32767" />
		<point x="-14808" y="123432" z="-3112" h="0" />
		<point x="-15688" y="123352" z="-3112" h="49151" />
		<point x="-16344" y="123336" z="-3112" h="16383" />
		<point x="-16152" y="123848" z="-3112" h="8191" />
		<point x="-15192" y="124696" z="-3112" h="24575" />
		<point x="-14936" y="123560" z="-3104" h="49151" />
		<point x="-14712" y="124264" z="-3112" h="26634" />
		<point x="-13128" y="124280" z="-3112" h="24575" />
		<point x="-13016" y="124872" z="-3112" h="32767" />
		<point x="-12520" y="123240" z="-3096" h="40959" />
		<point x="-13688" y="122856" z="-3104" h="57343" />
	</town>
	<town id="2" name="Dion">
		<point x="19080" y="146072" z="-3064" h="0" />
		<point x="19400" y="145256" z="-3104" h="24575" />
		<point x="19880" y="146232" z="-3112" h="37604" />
		<point x="21320" y="146216" z="-3152" h="43018" />
		<point x="21160" y="145384" z="-3088" h="0" />
		<point x="20872" y="144312" z="-3072" h="57343" />
		<point x="20888" y="144440" z="-3064" h="16383" />
		<point x="20696" y="145080" z="-3080" h="16383" />
		<point x="19848" y="144296" z="-3104" h="0" />
		<point x="20632" y="143704" z="-3072" h="57343" />
		<point x="19976" y="143160" z="-3040" h="0" />
		<point x="19336" y="142840" z="-3040" h="49151" />
		<point x="19576" y="143240" z="-3024" h="0" />
		<point x="19592" y="144360" z="-3088" h="16383" />
		<point x="18072" y="144824" z="-3040" h="40959" />
		<point x="17768" y="144584" z="-3048" h="40959" />
		<point x="18472" y="143960" z="-3048" h="37604" />
		<point x="18760" y="142616" z="-3040" h="21220" />
		<point x="17160" y="145528" z="-3040" h="53988" />
		<point x="16408" y="145096" z="-3008" h="32767" />
		<point x="17336" y="146120" z="-3080" h="32767" />
		<point x="16376" y="146440" z="-3120" h="0" />
		<point x="17272" y="147064" z="-3104" h="24575" />
		<point x="17128" y="146856" z="-3080" h="53988" />
		<point x="17944" y="147208" z="-3112" h="32767" />
		<point x="16568" y="142856" z="-2704" h="16383" />
		<point x="17368" y="141832" z="-2696" h="21220" />
		<point x="16168" y="141912" z="-2696" h="40959" />
		<point x="16040" y="142184" z="-2688" h="16383" />
	</town>
	<town id="3" name="Giran">
		<point x="81128" y="143688" z="-3528" h="27931" />
		<point x="80376" y="143784" z="-3528" h="16383" />
		<point x="80424" y="144440" z="-3528" h="0" />
		<point x="81272" y="145304" z="-3528" h="49151" />
		<point x="80584" y="144856" z="-3528" h="16383" />
		<point x="79928" y="145496" z="-3496" h="32767" />
		<point x="79464" y="146024" z="-3528" h="24575" />
		<point x="81912" y="146040" z="-3528" h="8191" />
		<point x="82680" y="147016" z="-3536" h="24575" />
		<point x="83128" y="146280" z="-3464" h="16383" />
		<point x="81256" y="147368" z="-3528" h="53988" />
		<point x="81160" y="147368" z="-3528" h="40959" />
		<point x="79432" y="146504" z="-3520" h="8191" />
		<point x="79240" y="146376" z="-3528" h="8191" />
		<point x="79256" y="148120" z="-3528" h="57343" />
		<point x="80072" y="147928" z="-3528" h="32767" />
		<point x="80264" y="147912" z="-3504" h="0" />
		<point x="80552" y="148408" z="-3528" h="24575" />
		<point x="78600" y="149448" z="-3592" h="0" />
		<point x="78008" y="148376" z="-3592" h="24575" />
		<point x="77688" y="148200" z="-3592" h="27931" />
		<point x="77224" y="147496" z="-3592" h="8191" />
		<point x="77880" y="147864" z="-3592" h="49151" />
		<point x="77240" y="148936" z="-3592" h="8191" />
		<point x="78600" y="149592" z="-3592" h="8191" />
		<point x="79256" y="148952" z="-3528" h="4836" />
		<point x="80072" y="149304" z="-3528" h="32767" />
		<point x="80360" y="149512" z="-3504" h="40959" />
		<point x="79272" y="150792" z="-3528" h="44315" />
		<point x="79960" y="150392" z="-3520" h="16383" />
		<point x="80088" y="150376" z="-3528" h="60699" />
		<point x="81144" y="150616" z="-3520" h="37604" />
		<point x="80808" y="149880" z="-3528" h="8191" />
		<point x="81240" y="152168" z="-3528" h="8191" />
		<point x="80680" y="152008" z="-3528" h="37604" />
		<point x="79992" y="150968" z="-3528" h="16383" />
		<point x="79272" y="152200" z="-3536" h="0" />
		<point x="81144" y="152776" z="-3528" h="37604" />
		<point x="82376" y="152488" z="-3528" h="8191" />
		<point x="82360" y="151320" z="-3528" h="8191" />
		<point x="81784" y="149928" z="-3528" h="19739" />
		<point x="81896" y="151192" z="-3528" h="53988" />
		<point x="83048" y="150520" z="-3512" h="0" />
		<point x="83416" y="150280" z="-3528" h="49151" />
		<point x="82056" y="149704" z="-3424" h="57343" />
		<point x="83944" y="148904" z="-3400" h="8191" />
		<point x="85672" y="148888" z="-3400" h="49151" />
		<point x="84600" y="148488" z="-3400" h="0" />
		<point x="84248" y="149336" z="-3400" h="24575" />
		<point x="85192" y="149832" z="-3392" h="57343" />
		<point x="85256" y="149976" z="-3400" h="24575" />
		<point x="85016" y="152312" z="-3528" h="0" />
		<point x="86360" y="153160" z="-3496" h="32767" />
		<point x="86520" y="153448" z="-3496" h="49151" />
		<point x="86616" y="149544" z="-3400" h="11547" />
		<point x="88184" y="149992" z="-3400" h="37604" />
		<point x="87768" y="148520" z="-3400" h="57343" />
		<point x="88376" y="147528" z="-3400" h="40959" />
		<point x="86360" y="146968" z="-3400" h="3355" />
		<point x="85928" y="146728" z="-3400" h="57343" />
		<point x="85096" y="145816" z="-3400" h="0" />
		<point x="84600" y="145080" z="-3400" h="0" />
		<point x="84312" y="143736" z="-3400" h="49151" />
		<point x="83672" y="144088" z="-3400" h="0" />
		<point x="82968" y="144728" z="-3528" h="32767" />
		<point x="81928" y="143800" z="-3528" h="57343" />
		<point x="84520" y="146600" z="-3400" h="40959" />
		<point x="83624" y="147096" z="-3400" h="4836" />
		<point x="81624" y="148568" z="-3472" h="32767" />
	</town>
	<town id="4" name="Oren">
		<point x="82600" y="52952" z="-1488" h="40959" />
		<point x="83464" y="53752" z="-1456" h="49151" />
		<point x="83528" y="53960" z="-1456" h="8191" />
		<point x="83656" y="54536" z="-1512" h="32767" />
		<point x="83304" y="54856" z="-1504" h="16383" />
		<point x="83288" y="55368" z="-1520" h="32767" />
		<point x="83736" y="55480" z="-1512" h="32767" />
		<point x="83704" y="56056" z="-1520" h="29412" />
		<point x="82776" y="56264" z="-1520" h="45796" />
		<point x="81368" y="56072" z="-1520" h="57343" />
		<point x="81480" y="55112" z="-1504" h="57343" />
		<point x="79976" y="56984" z="-1560" h="49151" />
		<point x="79432" y="56568" z="-1512" h="16383" />
		<point x="79192" y="56088" z="-1552" h="53988" />
		<point x="79512" y="55528" z="-1544" h="32767" />
		<point x="80088" y="54808" z="-1544" h="32767" />
		<point x="79896" y="54616" z="-1552" h="57343" />
		<point x="80104" y="53640" z="-1520" h="49151" />
		<point x="79784" y="53624" z="-1544" h="32767" />
		<point x="80440" y="52680" z="-1552" h="29412" />
		<point x="81288" y="54168" z="-1488" h="44315" />
		<point x="81992" y="54136" z="-1488" h="0" />
	</town>
	<town id="5" name="Aden">
		<point x="147688" y="20152" z="-2008" h="11547" />
		<point x="151080" y="21368" z="-2136" h="49151" />
		<point x="150248" y="21944" z="-2136" h="27931" />
		<point x="151048" y="23560" z="-2136" h="49151" />
		<point x="150888" y="25320" z="-2144" h="37604" />
		<point x="149480" y="24968" z="-2120" h="18939" />
		<point x="148808" y="25912" z="-2136" h="16383" />
		<point x="151064" y="28104" z="-2272" h="53988" />
		<point x="150744" y="28472" z="-2248" h="49151" />
		<point x="149816" y="30792" z="-2456" h="32767" />
		<point x="147784" y="31016" z="-2456" h="49151" />
		<point x="145112" y="30472" z="-2456" h="60699" />
		<point x="143656" y="29208" z="-2456" h="60699" />
		<point x="143416" y="26600" z="-2392" h="49151" />
		<point x="145864" y="25960" z="-2136" h="49151" />
		<point x="144168" y="25704" z="-2120" h="49151" />
		<point x="143608" y="24296" z="-2136" h="16383" />
		<point x="143800" y="23608" z="-2120" h="16383" />
		<point x="143896" y="22808" z="-2120" h="0" />
		<point x="143672" y="21208" z="-2136" h="16383" />
		<point x="145896" y="23528" z="-2112" h="40959" />
		<point x="145176" y="21048" z="-2136" h="60699" />
		<point x="146520" y="23160" z="-2008" h="27931" />
		<point x="146712" y="25032" z="-2008" h="40959" />
		<point x="147896" y="23784" z="-1984" h="27931" />
